//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuperacionRegistros.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RegistrosSoap")]
    public interface RegistrosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        RecuperacionRegistros.ServiceReference1.HelloWorldResponse HelloWorld(RecuperacionRegistros.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.HelloWorldResponse> HelloWorldAsync(RecuperacionRegistros.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento registrosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registros", ReplyAction="*")]
        RecuperacionRegistros.ServiceReference1.registrosResponse registros(RecuperacionRegistros.ServiceReference1.registrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registros", ReplyAction="*")]
        System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.registrosResponse> registrosAsync(RecuperacionRegistros.ServiceReference1.registrosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public RecuperacionRegistros.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(RecuperacionRegistros.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public RecuperacionRegistros.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(RecuperacionRegistros.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registros", Namespace="http://tempuri.org/", Order=0)]
        public RecuperacionRegistros.ServiceReference1.registrosRequestBody Body;
        
        public registrosRequest() {
        }
        
        public registrosRequest(RecuperacionRegistros.ServiceReference1.registrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registrosRequestBody {
        
        public registrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public RecuperacionRegistros.ServiceReference1.registrosResponseBody Body;
        
        public registrosResponse() {
        }
        
        public registrosResponse(RecuperacionRegistros.ServiceReference1.registrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrosResult;
        
        public registrosResponseBody() {
        }
        
        public registrosResponseBody(string registrosResult) {
            this.registrosResult = registrosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrosSoapChannel : RecuperacionRegistros.ServiceReference1.RegistrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrosSoapClient : System.ServiceModel.ClientBase<RecuperacionRegistros.ServiceReference1.RegistrosSoap>, RecuperacionRegistros.ServiceReference1.RegistrosSoap {
        
        public RegistrosSoapClient() {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecuperacionRegistros.ServiceReference1.HelloWorldResponse RecuperacionRegistros.ServiceReference1.RegistrosSoap.HelloWorld(RecuperacionRegistros.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            RecuperacionRegistros.ServiceReference1.HelloWorldRequest inValue = new RecuperacionRegistros.ServiceReference1.HelloWorldRequest();
            inValue.Body = new RecuperacionRegistros.ServiceReference1.HelloWorldRequestBody();
            RecuperacionRegistros.ServiceReference1.HelloWorldResponse retVal = ((RecuperacionRegistros.ServiceReference1.RegistrosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.HelloWorldResponse> RecuperacionRegistros.ServiceReference1.RegistrosSoap.HelloWorldAsync(RecuperacionRegistros.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            RecuperacionRegistros.ServiceReference1.HelloWorldRequest inValue = new RecuperacionRegistros.ServiceReference1.HelloWorldRequest();
            inValue.Body = new RecuperacionRegistros.ServiceReference1.HelloWorldRequestBody();
            return ((RecuperacionRegistros.ServiceReference1.RegistrosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecuperacionRegistros.ServiceReference1.registrosResponse RecuperacionRegistros.ServiceReference1.RegistrosSoap.registros(RecuperacionRegistros.ServiceReference1.registrosRequest request) {
            return base.Channel.registros(request);
        }
        
        public string registros() {
            RecuperacionRegistros.ServiceReference1.registrosRequest inValue = new RecuperacionRegistros.ServiceReference1.registrosRequest();
            inValue.Body = new RecuperacionRegistros.ServiceReference1.registrosRequestBody();
            RecuperacionRegistros.ServiceReference1.registrosResponse retVal = ((RecuperacionRegistros.ServiceReference1.RegistrosSoap)(this)).registros(inValue);
            return retVal.Body.registrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.registrosResponse> RecuperacionRegistros.ServiceReference1.RegistrosSoap.registrosAsync(RecuperacionRegistros.ServiceReference1.registrosRequest request) {
            return base.Channel.registrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecuperacionRegistros.ServiceReference1.registrosResponse> registrosAsync() {
            RecuperacionRegistros.ServiceReference1.registrosRequest inValue = new RecuperacionRegistros.ServiceReference1.registrosRequest();
            inValue.Body = new RecuperacionRegistros.ServiceReference1.registrosRequestBody();
            return ((RecuperacionRegistros.ServiceReference1.RegistrosSoap)(this)).registrosAsync(inValue);
        }
    }
}
